export const REVIEW_VOCAB = {
  gold: {
    prefixes: ["The 24K density is remarkable.", "Exceptional purity confirmed.", "A masterwork of physical bullion.", "The luster is breathtaking.", "A superior inflation hedge.", "The weight feels significant and authentic.", "Purity exceeded my private lab tests.", "A pristine addition to my holdings.", "The minted finish is world-class.", "Incredible craftsmanship on this bar."],
    middles: ["Verified the mass independently.", "The armored delivery protocol was precise.", "The craftsmanship is sovereign.", "Fits perfectly into my private estate vault.", "The price oracle provided a fair entry point.", "The concierge verified the hallmark instantly.", "Logistics were handled with total discretion.", "Settlement via BTC was seamless.", "The assay certificate is highly detailed.", "Physical custody was transferred flawlessly."],
    suffixes: ["Highly recommended for serious collectors.", "Will be acquiring more soon.", "Lume Vault remains my primary source.", "Flawless execution throughout.", "Discretion was absolute.", "A cornerstone of my wealth preservation.", "Five stars for the security protocol.", "The elite standard for gold trade.", "Simply unmatched in this industry.", "Sovereign quality."]
  },
  diamond: {
    prefixes: ["The VVS1 clarity is breathtaking.", "GIA report verified instantly.", "The fire and scintillation are superior.", "A significant addition to my estate.", "Mathematically perfect cut.", "The brilliance in natural light is staggering.", "Exceptional color grade confirmed.", "The stone's provenance is impeccable.", "A truly rare find in this carat weight.", "The depth of fire is mesmerizing."],
    middles: ["The light performance is incredible.", "Sourced via the Bespoke Hub perfectly.", "The provenance is impeccably clean.", "Far superior to the high-res photography.", "The security handshake was reassuring.", "Gemologist appraisal matched the GIA data.", "Hand-delivered in a secure, velvet-lined case.", "The settlement was fast and encrypted.", "Every facet reflects master-level cutting.", "The inclusion profile is virtually non-existent."],
    suffixes: ["A world-class gemstone.", "Exceeded every expectation.", "Truly a centerpiece acquisition.", "Exceptional brilliance.", "The ultimate legacy gift.", "Pure perfection.", "Investment grade quality.", "A breathtaking physical asset.", "Lume Vault is the only source I trust.", "Masterful."]
  },
  watch: {
    prefixes: ["The movement is pristine.", "Investment grade reference.", "A rare horological find.", "Condition is better than described.", "The caliber timing is flawless.", "The dial furniture is perfect.", "A significant reference for any collector.", "The case geometry remains sharp.", "Horological excellence defined.", "Unworn condition as promised."],
    middles: ["The patina is exactly as I wanted.", "Box and papers authenticated by concierge.", "Running well within COSC standards.", "A masterwork of mechanical engineering.", "Off-market sourcing at its finest.", "The complications function with crisp precision.", "Verified by my master watchmaker.", "The hand-delivery escort was professional.", "Settlement protocol was secure and discreet.", "The reference number matches all registry logs."],
    suffixes: ["An absolute masterpiece.", "Professional logistics throughout.", "The perfect vintage reference.", "A must-have for the vault.", "Elite service.", "Timeless acquisition.", "The pinnacle of my collection.", "Superlative quality.", "A legendary timepiece.", "Five-star concierge experience."]
  }
};